### PR TITLE
Reversed config files. Fixed #92.

### LINKED ISSUE #92: --config problems with 'defaults'
Generally it's cool to see the multiple --config flag feature.
But just now i was confused, when in my local config.yml (=last one provided) i specified
```
defaults:
  tag:
    foo
```
, called `openslides config --config highlevel-config.yml --config config.yml .` and it did not show up in the resulting compose file. To my understanding the last provided config will overrule previos ones.

If my config.yml looks like
```
services:
  backend:
    tag: foo
```
the substitution works as expected.
Thus i suspect there is not a problem within the config-merging-funtion-thingy but more specifcly in the handling of the defaults tag.

Also curiously changing the order of the provided config files will make the defaults substitution work as expected, so yeah. Somethings fishy here.

### PR DESCRIPTION
**Pull request by normanjaeckel**

### CODE REVIEW

**Comment by normanjaeckel** [comment]
@peb-adr Please test my new commit again (both cases). Thanks.

**Comment by normanjaeckel** [comment]
@ostcar: How can I get rid of reflect here? (I know you told me that you don't like such a third-party tool like [mergo](https://pkg.go.dev/github.com/imdario/mergo) but I need a smart solution to merge default and (multiple) custom config files. So this tool was nice (but I has this bug which is already issued for some months).

**Comment by ostcar** [comment]
There is the saying, that of you add a dependency, you take the responsibility for it.

I think I would not add it in this case. But I think that it it's ok tl if you want to add it.

If you add it? You should create a new file for the bug fix that needs reflect. And you could add a comment, that this file gets removed as soon as the bug is fixed mainstream.

**Comment by normanjaeckel** [comment]
But how can I avoid this dependency? Do I have to merge everything by hand e. g. with a custom method?

**Pull request merged**
