### PR TITLE
Let set-password and initial-data command use backend action service.

### PR DESCRIPTION
**Pull request by normanjaeckel**

### CODE REVIEW

**Comment by normanjaeckel** [comment]
See https://github.com/OpenSlides/openslides-backend/issues/1097 and https://github.com/OpenSlides/openslides-backend/issues/1096. Both issues have to be solved first.

**Comment by normanjaeckel** [comment]
Ok, I added the internal_auth_password. @peb-adr You may test this with updated backend.

**Comment by peb-adr** [comment]
I tested this in conjunction with https://github.com/OpenSlides/openslides-backend/pull/1105#pullrequestreview-834173398
and it woks well.
So these should be merged together

**Comment by normanjaeckel** [comment]
Merged together with https://github.com/OpenSlides/openslides-backend/pull/1105

**Pull request merged**
